export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  PROVIDER: 'PROVIDER',
  ADMIN: 'ADMIN',
} as const;

export const VERIFICATION_STATUS = {
  UNVERIFIED: 'UNVERIFIED',
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
} as const;

export const BOOKING_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  ON_THE_WAY: 'ON_THE_WAY',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const SERVICE_TYPES = {
  SMART_REPAIR: 'SMART_REPAIR',
  PREVENTIVE_MAINTENANCE: 'PREVENTIVE_MAINTENANCE',
  EMERGENCY_RESCUE: 'EMERGENCY_RESCUE',
} as const;

export const VEHICLE_TYPES = {
  MOTORCYCLE: 'MOTORCYCLE',
  SCOOTER: 'SCOOTER',
  CAR: 'CAR',
  OTHER: 'OTHER',
} as const;

export const SEVERITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

export const DEFAULT_SEARCH_RADIUS_KM = 15.0;
export const EMERGENCY_INITIAL_RADIUS_KM = 5.0;
export const EMERGENCY_EXPANDED_RADIUS_KM_1 = 10.0;
export const EMERGENCY_EXPANDED_RADIUS_KM_2 = 20.0;
